//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestAppStudy.WEB.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление студента.
        /// </summary>
        public static string Add_student {
            get {
                return ResourceManager.GetString("Add_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление предмета.
        /// </summary>
        public static string Add_subject {
            get {
                return ResourceManager.GetString("Add_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление преподавателя.
        /// </summary>
        public static string Add_teacher {
            get {
                return ResourceManager.GetString("Add_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенные вами пароль и подтверждение пароля не совпадают.
        /// </summary>
        public static string Alert_psw_not_match {
            get {
                return ResourceManager.GetString("Alert_psw_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить студента.
        /// </summary>
        public static string Assign_student {
            get {
                return ResourceManager.GetString("Assign_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение студентов.
        /// </summary>
        public static string Assign_student_to_subj {
            get {
                return ResourceManager.GetString("Assign_student_to_subj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение предмета и преподавателя.
        /// </summary>
        public static string Assign_subj_tech {
            get {
                return ResourceManager.GetString("Assign_subj_tech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначение предмета.
        /// </summary>
        public static string Assign_subject {
            get {
                return ResourceManager.GetString("Assign_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назначить предмет.
        /// </summary>
        public static string Assing_subj_to_teach {
            get {
                return ResourceManager.GetString("Assing_subj_to_teach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста, авторизуйтесь, чтобы получить доступ к сайту..
        /// </summary>
        public static string Authorization_ask {
            get {
                return ResourceManager.GetString("Authorization_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Btn_add {
            get {
                return ResourceManager.GetString("Btn_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить комментарий.
        /// </summary>
        public static string Btn_add_comment {
            get {
                return ResourceManager.GetString("Btn_add_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Btn_cancel {
            get {
                return ResourceManager.GetString("Btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить предмет.
        /// </summary>
        public static string Btn_cancel_subj {
            get {
                return ResourceManager.GetString("Btn_cancel_subj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Btn_edit {
            get {
                return ResourceManager.GetString("Btn_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У меня уже есть аккаунт.
        /// </summary>
        public static string Btn_have_account {
            get {
                return ResourceManager.GetString("Btn_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть комментарии.
        /// </summary>
        public static string Btn_hide_comments {
            get {
                return ResourceManager.GetString("Btn_hide_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Btn_login {
            get {
                return ResourceManager.GetString("Btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Btn_logout {
            get {
                return ResourceManager.GetString("Btn_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string Btn_no {
            get {
                return ResourceManager.GetString("Btn_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У меня еще нет аккаунта.
        /// </summary>
        public static string Btn_not_have_account {
            get {
                return ResourceManager.GetString("Btn_not_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрировать.
        /// </summary>
        public static string Btn_register {
            get {
                return ResourceManager.GetString("Btn_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Btn_remove {
            get {
                return ResourceManager.GetString("Btn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Btn_save {
            get {
                return ResourceManager.GetString("Btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать комментарии.
        /// </summary>
        public static string Btn_show_comments {
            get {
                return ResourceManager.GetString("Btn_show_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Btn_yes {
            get {
                return ResourceManager.GetString("Btn_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить предмет.
        /// </summary>
        public static string Cancel_subject {
            get {
                return ResourceManager.GetString("Cancel_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите студента.
        /// </summary>
        public static string Choose_student {
            get {
                return ResourceManager.GetString("Choose_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите предмет.
        /// </summary>
        public static string Choose_subject {
            get {
                return ResourceManager.GetString("Choose_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите преподавателя.
        /// </summary>
        public static string Choose_teacher {
            get {
                return ResourceManager.GetString("Choose_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Содержание комментария.
        /// </summary>
        public static string Comment_description {
            get {
                return ResourceManager.GetString("Comment_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артур Жунусов.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес электронной почты.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы вошли как.
        /// </summary>
        public static string EntryText {
            get {
                return ResourceManager.GetString("EntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список назначенных студентов.
        /// </summary>
        public static string List_assigned_students {
            get {
                return ResourceManager.GetString("List_assigned_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список всех студентов.
        /// </summary>
        public static string List_students {
            get {
                return ResourceManager.GetString("List_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список всех предметов.
        /// </summary>
        public static string List_subjects {
            get {
                return ResourceManager.GetString("List_subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список всех преподавателей.
        /// </summary>
        public static string List_teachers {
            get {
                return ResourceManager.GetString("List_teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт разработал.
        /// </summary>
        public static string Made_by {
            get {
                return ResourceManager.GetString("Made_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string Password_confirm {
            get {
                return ResourceManager.GetString("Password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личные данные.
        /// </summary>
        public static string Personal_info {
            get {
                return ResourceManager.GetString("Personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите комментарий.
        /// </summary>
        public static string Ph_comment_description {
            get {
                return ResourceManager.GetString("Ph_comment_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите адрес электронной почты.
        /// </summary>
        public static string Ph_email {
            get {
                return ResourceManager.GetString("Ph_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите имя.
        /// </summary>
        public static string Ph_firstname {
            get {
                return ResourceManager.GetString("Ph_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите фамилию.
        /// </summary>
        public static string Ph_lastname {
            get {
                return ResourceManager.GetString("Ph_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите пароль.
        /// </summary>
        public static string Ph_password {
            get {
                return ResourceManager.GetString("Ph_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повторите ввод пароля.
        /// </summary>
        public static string Ph_password_confirm {
            get {
                return ResourceManager.GetString("Ph_password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите отчество.
        /// </summary>
        public static string Ph_patronymic {
            get {
                return ResourceManager.GetString("Ph_patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату начала обучения.
        /// </summary>
        public static string Ph_studystart {
            get {
                return ResourceManager.GetString("Ph_studystart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите короткое описание предмета.
        /// </summary>
        public static string Ph_subj_description {
            get {
                return ResourceManager.GetString("Ph_subj_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название предмета.
        /// </summary>
        public static string Ph_subj_title {
            get {
                return ResourceManager.GetString("Ph_subj_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя пользователя.
        /// </summary>
        public static string Ph_username {
            get {
                return ResourceManager.GetString("Ph_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приватный.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОЕКТ &quot;УЧЕБНЫЙ ПРОЦЕСС&quot;.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публичный.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список предметов студента (предмет - преподаватель).
        /// </summary>
        public static string Student_subj_list {
            get {
                return ResourceManager.GetString("Student_subj_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТУДЕНТЫ.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала обучения.
        /// </summary>
        public static string Study_begining {
            get {
                return ResourceManager.GetString("Study_begining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание предмета.
        /// </summary>
        public static string Subj_description {
            get {
                return ResourceManager.GetString("Subj_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРЕДМЕТЫ.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о преподаваемых предметах.
        /// </summary>
        public static string Taught_subj_info {
            get {
                return ResourceManager.GetString("Taught_subj_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаваемые предметы.
        /// </summary>
        public static string Taught_subjects {
            get {
                return ResourceManager.GetString("Taught_subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРЕПОДАВАТЕЛИ.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО Студента.
        /// </summary>
        public static string Title_stu_name {
            get {
                return ResourceManager.GetString("Title_stu_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название предмета.
        /// </summary>
        public static string Title_subject {
            get {
                return ResourceManager.GetString("Title_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО Преподавателя.
        /// </summary>
        public static string Title_teach_name {
            get {
                return ResourceManager.GetString("Title_teach_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть меню.
        /// </summary>
        public static string Tt_close_menu {
            get {
                return ResourceManager.GetString("Tt_close_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть резюме.
        /// </summary>
        public static string Tt_cv {
            get {
                return ResourceManager.GetString("Tt_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите, чтобы пройти авторизацию.
        /// </summary>
        public static string Tt_login {
            get {
                return ResourceManager.GetString("Tt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактрование личных данных.
        /// </summary>
        public static string Tt_personal_info {
            get {
                return ResourceManager.GetString("Tt_personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите, чтобы пройти регистрацию.
        /// </summary>
        public static string Tt_register {
            get {
                return ResourceManager.GetString("Tt_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
